# Site settings
title: DC Tractor 
description: This is the website set up by Yi Du for the DC Tractor Competition.
baseurl: "" 
url: ""

# User setting
owner: DC Tractor
email: dctractorcompetition@gmail.com
wechat_username:
github_username: dctractor
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# Build settings
markdown: kramdown
